{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fleet-workspace-controller.serviceAccountName" . }}
  labels:
    {{- include "fleet-workspace-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fleet-workspace-controller.fullname" . }}-role
  labels:
    {{- include "fleet-workspace-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fleet-workspace-controller.fullname" . }}-binding
  labels:
    {{- include "fleet-workspace-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fleet-workspace-controller.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "fleet-workspace-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
